### PR TITLE
NetHunter support ?

### PR DESCRIPTION
**Pull request by saidsay-so**
Hello,
I created/applied some patches to support NetHunter. 
HID support patch from there : https://github.com/pelya/android-keyboard-gadget/blob/master/kernel-3.18.patch
and injection patch from there :  http://patches.aircrack-ng.org/mac80211.compat08082009.wl_frag+ack_v1.patch
I created a new defconfig because I need to add support for SysV IPC, modules and some drivers for external card and I created myself the CD-ROM emulation code because I didn't find a patch for it.
Would you want to merge them ?

### CODE REVIEW

**Comment by msfjarvis** [comment]
1) full of kangs
2) adds an unnecessary defconfig, which again, is mostly kanged.

**Comment by lordarcadius** [comment]
Duh! Why you kanged the commits? Lmao, I won't merge these commits without proper authorship. @MSF-Jarvis is right. K bye, closing PR. Thanks for interest. You can give another PR with proper authorship.

**Comment by MusiKid** [comment]
arf ok sorry.

**Comment by MusiKid** [comment]
So now ?

**Comment by msfjarvis** [comment]
> You can give another PR with proper authorship.

@MusiKid was that sentence too difficult to understand

**Comment by saidsay-so** [comment]
sorry again that what I did lmao

**Comment by ghost** [comment]
@MSF-Jarvis That comment is "Harsh-ed"

**Comment by saidsay-so** [comment]
I understand if he is angry, I am a "noob" with these things

**Comment by ghost** [comment]
@MusiKid @LordArcadius give O plz

**Comment by saidsay-so** [comment]
ok so I stop the flood (sorry again)

**Comment by lordarcadius** [comment]
@Zephoro plox, O is supported lmao

**Comment by arn4v** [comment]
@LordArcadius Kek

**Comment by ghost** [comment]
@LordArcadius Then support P

**Comment by saidsay-so** [comment]
And I have to precise that I never kanged anyone because these are my commits but I used several patches.
Explained all here : https://github.com/LordArcadius/electrablue_mido/pull/7

**Comment by arn4v** [comment]
@MusiKid Kek

**Comment by ghost** [comment]
@arn4v Gib RR O

**Comment by arn4v** [comment]
@Zephoro Nu

**Comment by ghost** [comment]
@arn4v Y

**Comment by ghost** [comment]
@Zephoro Btw the PR's closed and why are we still commenting ;_;

**Comment by arn4v** [comment]
@Zephoro cuz yolo

**Comment by ghost** [comment]
@arn4v ;-;

**Comment by arn4v** [comment]
@Zephoro cuz github tg bot is thug

**Comment by ghost** [comment]
@arn4v Yus. Instant comments

**Comment by ghost** [comment]
@Zephoro Instant spam too

**Comment by ghost** [comment]
@Zephoro Why am I tagging myself

**Comment by saidsay-so** [comment]
wtf what is so funny ?

**Comment by ghost** [comment]
@MusiKid Nothing sur. Enjoy kanging

**Comment by arn4v** [comment]
@MusiKid 😆

**Comment by arn4v** [comment]
@MusiKid Life is.

**Comment by saidsay-so** [comment]
so you see my new PR ?
or my edited comment ?

**Comment by adekmaulana** [comment]
@MusiKid Kek

**Comment by saidsay-so** [comment]
but I'm not kanging anyone :sob: !
Did you take a look at my new PR ?

**Comment by saidsay-so** [comment]
So I paste my new PR if you don't have take a look on it :
Hello,
I am very sorry for the flood but I mispoked when I say "commits", I wanted to say patches.
I didn't want to kang anyone (to be honest I needed to google it because I didn't know what it means lmao).

Here is the patch for injection support : http://patches.aircrack-ng.org/mac80211.compat08082009.wl_frag+ack_v1.patch
and for HID emulation support : https://github.com/pelya/android-keyboard-gadget/blob/master/kernel-3.18.patch
I created a new defconfig because NetHunter need to enable the SysV IPC and to add new device drivers for external wifi card (https://github.com/offensive-security/kali-nethunter/wiki/Modifying-the-Kernel).
And I didn't find a recent patch for CD-ROM emulation so I coded it myself (The only I find was there :https://github.com/CyanogenMod/android_kernel_lge_hammerhead/commit/46bd47757a9f34c1d95dd2620414893212fb0526 but is not working in new versions so).
Sorry again for the flood(do you forgive me ? :sob: ).

**Comment by arn4v** [comment]
@MusiKid Chill bru

**Comment by saidsay-so** [comment]
@arn4v sorry I'm a little stressed with my school exams so

**Comment by saidsay-so** [comment]
And BTW I don't like to steal people work.

**Comment by ghost** [comment]
@MusiKid Who doesn't ;_;

**Comment by arn4v** [comment]
@MusiKid Kbru

**Comment by ghost** [comment]
what's going on

**Pull request closed without merging**
