### PR TITLE
Add USB HID gadget suport

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lordarcadius** [comment]
@h4waii What the hell is invalid email ;_;

**Comment by ghost** [comment]
It's what GH uses when you don't want to publicly share your email address.

**Comment by arn4v** [comment]
@h4waii 🌚

**Comment by saidsay-so** [comment]
This is what i wanted to commit lmao !
How did you add the (invalid) email address ?

**Comment by lordarcadius** [comment]
@h4waii PR merged! Thanks for contribution.

**Pull request merged**
